os: linux
dist: xenial
language: node_js
node_js:
  - 10
before_script:
  - npm run build
script: eleventy
deploy:
  strategy: git
  local_dir: _site
  provider: pages
  edge: true
  token: $GITHUB_TOKEN  # Set in travis-ci.com dashboard, marked secure
  keep_history: true
  fqdn: scotthood.co.uk
  target_branch: gh-pages
  on:
    branch: dev
